import HeaderNavbar from "@/components/layout/header";
import "../globals.css";
import Footer from "@/components/layout/footer";
import { Montserrat } from "next/font/google";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({
  //weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <HeaderNavbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
